# Lychee configuration for link checking

# Cache results for faster subsequent runs
cache = true

# Timeout settings
timeout = 20

# Maximum number of redirects to follow
max_redirects = 5

# Accept status codes (2xx by default)
accept = [200, 203, 204, 206, 300, 301, 302, 303, 304, 307, 308]

# Retry settings
retry_wait_time = 2
max_retries = 3

# Exclude specific paths from being checked
exclude_path = ["projects/example_team/", "**/upstream/**", "**/snapshot/**"] 